name: Update README Table of Contents

on:
  workflow_dispatch:  # Manual trigger from the GitHub UI
  pull_request:
    paths:
      - 'challenges/**'
      - '.github/scripts/update_readme.py'  # Optional, if script is updated
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run TOC update script
        run: python .github/scripts/update_readme.py
      - name: Setup Git
        uses: qoomon/actions--setup-git@v1
        with:
          user: bot

      - name: Commit updated README
        run: |
          git add README.md
          git commit -m "Chore: Update README TOC"
          git push
