name: Validate New Challenge

on:
  pull_request:
    paths:
      - 'challenges/**'
jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.head_ref }}

    - name: Set up Python (for validation script)
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install PyYAML
      run: pip install pyyaml
      
    - name: Validate Challenges
      run: python .github/scripts/validate_challenge_structure.py
